version: "2.4"

services:

  # main service
  talebook:
    restart: always
    image: talebook/talebook
    volumes:
      - /data/demo:/data
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - douban-rs-api

  # optional, for meta plugins
  # please set "http://douban-rs-api" in settings
  douban-rs-api:
    restart: always
    image: ghcr.io/cxfksword/douban-api-rs
